ignoredBuiltDependencies:
  - azure-functions-core-tools
  - pkcs11js
  - protobufjs

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  minimatch@>=8.0.0 <8.0.5: '>=8.0.5'
  minimatch@>=8.0.0 <8.0.6: '>=8.0.6'
