#helm install ca-certs -f values/noproxy-and-novault/genesis.yaml -n supplychain-net fabric-genesis
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: kubernetes
  proxy:
    provider: none
    externalUrlSuffix: supplychain-net

organizations:
  - name: supplychain
    orderers:
      - name: orderer1
        ordererAddress: orderer1.supplychain-net:7050
    peers:
      - name: peer0
        peerAddress: peer0.supplychain-net:7051
      - name: peer1
        peerAddress: peer1.supplychain-net:7051

consensus: raft
channels:
  - name: allchannel
    consortium: SupplyChainConsortium
    orderers:
      - supplychain
    participants:
      - supplychain

settings:
  removeConfigMapOnDelete: true
