##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
# The following are for overriding global values
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: kubernetes
    role: vault-role
    network: fabric

image:
  fabricTools: ghcr.io/hyperledger/bevel-fabric-tools
  alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
  pullSecret:

#Provide orderer details
orderers:
  - name: orderer1
    adminAddress: orderer1.supplychain-net:7055
