name: Deploy Function App(s) to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/functions/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Azure CLI Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Set up Python version'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        working-directory: ./infra/functions/IoTHubProcessor
        run: |
          pushd ./ # Assumes your function_app.py is in the root
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: deploy-iot-hub-processor-function
        with:
          app-name: 'bk-of-energy-modifier'
          package: './infra/functions/IoTHubProcessor'
          publish-profile: ${{ secrets.AZURE_MODIFIER_FUNCTIONAPP_PROFILE }}

      # Placeholder for other Azure Functions
