name: Deploy Python Function App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/functions/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Archive the source code of the function `process_iot_hub_message_artifact`'
        uses: actions/upload-artifact@v4
        with:
          name: process_iot_hub_message_artifact
          path: ./infra/functions/process_iot_hub_message

      - name: 'Archive the source code of the function `cosmos_db_writer`'
        uses: actions/upload-artifact@v4
        with:
          name: cosmos_db_writer_artifact
          path: ./infra/functions/cosmos_db_writer

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - name: process_iot_hub_message
            app: bk-of-energy-modifier
          - name: cosmos_db_writer
            app: bk-of-energy-writer
    needs: build
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ${{ matrix.function.name }}
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ matrix.function.app }}
          package: ./infra/functions/${{ matrix.function.name }}