name: Deploy Python Function App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/functions/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Archive the function app source code'
        uses: actions/upload-artifact@v4
        with:
          name: iot-hub-processor-func-artifact
          path: ./infra/functions/IoTHubProcessor

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      id-token: write

    steps:
      - name: 'Download deployment artifact'
        uses: actions/download-artifact@v4
        with:
          name: iot-hub-processor-func-artifact

      - name: Azure CLI Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy IoTHubProcessor function'
        uses: Azure/functions-action@v1
        id: deploy-iot-hub-processor-func
        with:
          app-name: "bk-of-energy-modifier"
          package: "."