name: Deploy Python Function App to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/functions/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build process_iot_hub_message
        run: |
          pip install -r requirements.txt --target ./.python_packages/lib/site-packages
        working-directory: ./infra/functions/process_iot_hub_message

      - name: Archive process_iot_hub_message
        uses: actions/upload-artifact@v4
        with:
          name: process_iot_hub_message_artifact
          path: ./infra/functions/process_iot_hub_message

      - name: Build cosmos_db_writer
        run: |
          pip install -r requirements.txt --target ./.python_packages/lib/site-packages
        working-directory: ./infra/functions/cosmos_db_writer

      - name: Archive cosmos_db_writer
        uses: actions/upload-artifact@v4
        with:
          name: cosmos_db_writer_artifact
          path: ./infra/functions/cosmos_db_writer

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - name: process_iot_hub_message
            app: bk-of-energy-modifier
          - name: cosmos_db_writer
            app: bk-of-energy-cosmodb-writer
    needs: build

    steps:
      - name: Download ${{ matrix.function.name }} artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.function.name }}_artifact
          path: ./infra/functions/${{ matrix.function.name }}

      - name: Deploy ${{ matrix.function.name }}
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ matrix.function.app }}
          package: ./infra/functions/${{ matrix.function.name }}
          publish-profile: ${{ secrets[format('AZURE_FUNCTIONAPP_PUBLISH_PROFILE_{0}', matrix.function.name)] }}